/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ESCAPE_ATTEMPTS INT NOT NULL,
    NEUTERED BOOLEAN,
    WEIGHT_KG DECIMAL NOT NULL
)
ALTER TABLE animals
ADD species TEXT;
CREATE TABLE owners(
    ID SERIAL PRIMARY KEY NOT NULL,
    FULL_NAME TEXT NOT NULL,
    AGE INT NOT NULL
);
CREATE TABLE species(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);
ALTER TABLE animals DROP COLUMN id;
ALTER TABLE animals
ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals
ADD COLUMN species_id INT,
    ADD CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(ID);
ALTER TABLE animals
ADD COLUMN owner_id INT,
    ADD CONSTRAINT fk_owners FOREIGN KEY(owner_id) REFERENCES owners(ID);

CREATE TABLE vets(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    AGE INT NOT NULL,
    DATA_OF_GRADUATION DATE NOT NULL
);

CREATE TABLE specializations(
    ID SERIAL PRIMARY KEY,
    SPECIES_ID INT NOT NULL,
    VETS_ID INT NOT NULL,
    CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id) ON DELETE CASCADE,
    CONSTRAINT fk_vets FOREIGN KEY(vet_id) REFERENCES vets(id) ON DELETE CASCADE
);

CREATE TABLE visits(
    ID SERIAL PRIMARY KEY,
    ANIMALS_ID INT NOT NULL,
    VETS_ID INT NOT NULL,
    DATE DATE NOT NULL,
    CONSTRAINT fk_animals FOREIGN KEY(animals_id) REFERENCES animals(id),
    CONSTRAINT fk_vets FOREIGN KEY(vets_id) REFERENCES vets(id)
);

ALTER TABLE owners ADD COLUMN email VARCHAR(120);

DROP TABLE visits;

CREATE TABLE visits(
    ID SERIAL PRIMARY KEY,
    ANIMAL_ID INT NOT NULL,
    VET_ID INT NOT NULL,
    DATE_OF_VISIT DATE NOT NULL,
    CONSTRAINT fk_animals FOREIGN KEY(animal_id) REFERENCES animals(id),
    CONSTRAINT fk_vets FOREIGN KEY(vet_id) REFERENCES vets(id)
);

CREATE INDEX visits_animal_id ON visits(animal_id);
CREATE INDEX visits_vet_id ON visits(vet_id);
CREATE INDEX owners_email ON owners(email);