/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ESCAPE_ATTEMPTS INT NOT NULL,
    NEUTERED BOOLEAN,
    WEIGHT_KG DECIMAL NOT NULL
)
ALTER TABLE animals
ADD species TEXT;
CREATE TABLE owners(
    ID SERIAL PRIMARY KEY NOT NULL,
    FULL_NAME TEXT NOT NULL,
    AGE INT NOT NULL
);
CREATE TABLE species(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);
ALTER TABLE animals DROP COLUMN id;
ALTER TABLE animals
ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals
ADD COLUMN species_id INT,
    ADD CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(ID);
ALTER TABLE animals
ADD COLUMN owner_id INT,
    ADD CONSTRAINT fk_owners FOREIGN KEY(owner_id) REFERENCES owners(ID);